name: Kinsta CI Course Project

on:
  push:
    branches: [ "main" ]
  
permissions:
  contents: read

jobs:

  php-tests:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v3
    
    - name: Test code for errors
    run: php -1 index.php
    
  # This workflow contains a single job called "build"
  build:
  
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
